# Generated by Django 3.0.3 on 2020-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adresseuser_compteactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresseuser',
            name='codeActivation',
            field=models.IntegerField(default=123456),
        ),
    ]
