# Generated by Django 3.0.3 on 2020-05-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['departement'], 'verbose_name': 'adresseUser'},
        ),
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='codeActivation',
            field=models.IntegerField(default=123456),
        ),
        migrations.AddField(
            model_name='profile',
            name='compteActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='departement',
            field=models.CharField(choices=[('1', 'Ain'), ('2', 'Aisne'), ('3', 'Allier'), ('75', 'Paris'), ('78', 'Yvelines'), ('91', 'Essonne'), ('92', 'Hauts-de-Seine'), ('93', 'Seine-Saint-Denis'), ('94', 'Val-de-Marne'), ('95', "Val d'Oise")], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='ville',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='AdresseUser',
        ),
    ]
