# Generated by Django 3.0.3 on 2020-05-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200508_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile-pics/default.jpg', null=True, upload_to='profile-pics'),
        ),
    ]
