# Generated by Django 3.0.3 on 2020-05-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_foyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foyer',
        ),
    ]
