# Generated by Django 3.0.3 on 2020-05-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_foyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='res1',
            field=models.CharField(choices=[('Viande', 'Viande'), ('Gluten', 'Gluten'), ('Lactose', 'Lactose'), ('Fruits secs', 'Fruits secs'), ('Vide', 'Vide')], default='Vide', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='res2',
            field=models.CharField(choices=[('Viande', 'Viande'), ('Gluten', 'Gluten'), ('Lactose', 'Lactose'), ('Fruits secs', 'Fruits secs'), ('Vide', 'Vide')], default='Vide', max_length=50),
        ),
    ]
