# Generated by Django 3.0.3 on 2020-05-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200510_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='res1',
            new_name='res',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='res2',
        ),
    ]
