# Generated by Django 3.0.3 on 2020-05-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='restriction2',
            field=models.CharField(choices=[('Viande', 'Viande'), ('Gluten', 'Gluten'), ('Lactose', 'Lactose'), ('Fruits secs', 'Fruits secs'), ('Vide', 'Vide')], default='Vide', max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='restriction',
            field=models.CharField(choices=[('Viande', 'Viande'), ('Gluten', 'Gluten'), ('Lactose', 'Lactose'), ('Fruits secs', 'Fruits secs'), ('Vide', 'Vide')], default='Vide', max_length=100),
        ),
    ]
