# Generated by Django 3.0.3 on 2020-05-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='restriction2',
        ),
    ]
